# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perkins < Formula
  desc "Braille ASCII pixel art editor for the terminal"
  homepage "https://github.com/Mr-Robot-err-404/perkins"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.3/perkins_darwin_amd64.tar.gz"
      sha256 "c8246f3106a625208b64436a2b0615d9c8f3f563f507012922d5e983f51cc357"

      define_method(:install) do
        bin.install "perkins"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.3/perkins_darwin_arm64.tar.gz"
      sha256 "f298c198982da95e9078abd75e54d8011c465e2b6bbf417c5799c368761a3c07"

      define_method(:install) do
        bin.install "perkins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.3/perkins_linux_amd64.tar.gz"
      sha256 "fb4d5f7b5af8c8b99cef21d14e13d8d2676683858202511d76dfc5e8cacb2e40"
      define_method(:install) do
        bin.install "perkins"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.3/perkins_linux_arm64.tar.gz"
      sha256 "c32dfc7ca29024abc64ff88e6a5d016ffd655623e5e1b4cb92b0df8a11b17f3e"
      define_method(:install) do
        bin.install "perkins"
      end
    end
  end
end
