# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perkins < Formula
  desc "Braille ASCII pixel art editor for the terminal"
  homepage "https://github.com/Mr-Robot-err-404/perkins"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.1/perkins_darwin_amd64.tar.gz"
      sha256 "3c3103cdd85a7151d0b4a54cdbec25b5aaece32065f5ab012056218b40ea4c6f"

      define_method(:install) do
        bin.install "perkins"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.1/perkins_darwin_arm64.tar.gz"
      sha256 "870259da2fb17da4f22fd5cd05651b7a173d0e0505869a9ccf017cc4eacb0da1"

      define_method(:install) do
        bin.install "perkins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.1/perkins_linux_amd64.tar.gz"
      sha256 "46809b548571e2d8937643ff44e1bf0655a5814345d8abd94ff1e79989603f6e"
      define_method(:install) do
        bin.install "perkins"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.1/perkins_linux_arm64.tar.gz"
      sha256 "817b15c451b1aecea983ef84133fef8468cb8902264816a96500e2e4d55a5d4b"
      define_method(:install) do
        bin.install "perkins"
      end
    end
  end
end
