# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Perkins < Formula
  desc "Braille ASCII pixel art editor for the terminal"
  homepage "https://github.com/Mr-Robot-err-404/perkins"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.4/perkins_darwin_amd64.tar.gz"
      sha256 "d23340f5ad67a08247f3bd62d9ee9fe267f5292c79732be8b11091b699bbdda2"

      define_method(:install) do
        bin.install "perkins"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.4/perkins_darwin_arm64.tar.gz"
      sha256 "645bb4c6d69bef19dcbce120dfd4b6c2d802f01b082c2cef3f0668300dbd79ef"

      define_method(:install) do
        bin.install "perkins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.4/perkins_linux_amd64.tar.gz"
      sha256 "bbc6c75c846198ee612c5dd44dbc2cab1fd4829e669ec340d4481a9c6f0276b3"
      define_method(:install) do
        bin.install "perkins"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mr-Robot-err-404/perkins/releases/download/v0.1.4/perkins_linux_arm64.tar.gz"
      sha256 "4ffd517795b0f63a64e55b0e204aa5907dce800e65d374fb798bc4bd8556b596"
      define_method(:install) do
        bin.install "perkins"
      end
    end
  end
end
